-- 01_demo.sql
-- Purpose : prove that the DB and script-hooks work
-- Location: ./db/scripts/setup      (mounted to /opt/oracle/scripts/setup)
-- Effect   : runs **once** on the very first container start-up

WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

-- 1) Work inside the PDB so the objects are visible to ORDS/APEX
ALTER SESSION SET CONTAINER = ORCLPDB1;

-- 2) Create a throw-away schema for demo work
CREATE USER demo IDENTIFIED BY demo
  DEFAULT TABLESPACE users
  QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO demo;

-- 3) Switch to that schema
CONNECT demo/demo

-- 4) Create a toy table and seed data
CREATE TABLE hello_world (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message    VARCHAR2(100)  NOT NULL,
  created_at TIMESTAMP      DEFAULT SYSTIMESTAMP
);

INSERT INTO hello_world (message)
VALUES ('Hello from Oracle in Docker!');

COMMIT;
EXIT;
